### PR TITLE
Added my portfolio 🎉

### PR DESCRIPTION
**Pull request by TomasRoj**

### CODE REVIEW

**Comment by blackbird71SR** [comment]
Great Work!👏👏👏

**Comment by TomasRoj** [comment]
Hi, I cannot see my pull request merged on my hactoberfest account. Is there some problem?

**Comment by blackbird71SR** [comment]
Hey, don't worry! There is 7 days review period for maintainers(like me for this project), to label PR as 'spam' or 'invalid'. If that does not happen in 7 days, they will mark PR as successful. Even mine is showing the same.

**Comment by TomasRoj** [comment]
Thanks

**Pull request merged**
